extends:
  - cheminfo-typescript
  - neptune-react
settings:
  import/resolver:
    node:
      extensions: ['.js', '.ts', '.tsx']
rules:
  '@typescript-eslint/explicit-function-return-type': off
  react/jsx-no-bind: off
